version: '2'
volumes:
  development_db:
    driver: 'local'
services:
  server:
    build:
      context: .
      dockerfile: ./dockers/local/server/Dockerfile
    environment:
      TZ: Japan
    extends:
      file: ./dockers/local/db/password.yml
      service: password
    ports:
      - '80:3000'
    volumes:
      - .:/var/www/travel_note
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: ./dockers/local/db/Dockerfile
    environment:
      TZ: Japan
    volumes:
      - development_db:/var/lib/mysql
    extends:
      file: ./dockers/local/db/password.yml
      service: password
    ports:
      - '3306:3306'
